# ML iris dataset
Taken from https://www.youtube.com/watch?v=tNa99PG8hR8

ML using the famous iris dataset

In [20]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

iris = load_iris()
print(iris.feature_names)
print(iris.target_names)
print(iris.data[0])
print(iris.target[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[ 5.1  3.5  1.4  0.2]
0


In [ ]:
# Show all data
for i in range(len(iris.target)):
    print("Row {}\t: Features {} : Label {}".format(i, iris.data[i], iris.target[i]))

In [19]:
# Remove some data for testing
# Use the first ones
test_idx = [0, 50, 100]

# training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

In [21]:
# train the classifier
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [25]:
# now let's predict
print(iris.target_names)
print(test_target)

prediction = clf.predict(test_data)
print(prediction)

['setosa' 'versicolor' 'virginica']
[0 1 2]
[0 1 2]


In [31]:
# try to visualize the tree
tree.export_graphviz(clf, 
                     out_file='tree.dot', 
                     impurity=False,
                     filled=True, 
                     rounded=True,
                     feature_names=iris.feature_names,
                     class_names=iris.target_names)
# on the terminal run (graphviz needs to be installed)
# dot -Tpng tree.dot -o tree.png